'use client';

import React from 'react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { AlertCircle } from 'lucide-react';
import { Alert, AlertDescription } from '@/components/ui/alert';
import InterviewSimulator from './_components/InterviewSimulator';

export default function InterviewSimulatorPage() {
  return (
    <div className="container mx-auto p-6 space-y-6">
      {/* Header */}
      <div className="space-y-2">
        <h1 className="text-3xl font-bold">AI Interview Simulator</h1>
        <p className="text-muted-foreground">
          Practice interviews with our AI-powered 3D avatar interviewer with real-time speech recognition and lip-sync
        </p>
      </div>

      {/* Important Notice */}
      <Alert>
        <AlertCircle className="h-4 w-4" />
        <AlertDescription>
          <strong>Requirements:</strong> This feature requires a backend server and Google Cloud credentials.
          Make sure the backend is running on <code className="bg-muted px-1 py-0.5 rounded">http://localhost:5000</code>
        </AlertDescription>
      </Alert>

      {/* Main Simulator */}
      <Card className="p-6">
        <InterviewSimulator />
      </Card>

      {/* Instructions */}
      <Card className="p-6">
        <h2 className="text-xl font-semibold mb-4">How to Use</h2>
        <ol className="list-decimal list-inside space-y-2 text-muted-foreground">
          <li>Click "Start Interview" to begin</li>
          <li>Allow microphone and camera access when prompted</li>
          <li>The AI interviewer will ask you questions</li>
          <li>Speak your answers clearly - the avatar will listen</li>
          <li>The AI will generate follow-up questions based on your responses</li>
          <li>Click "End Interview" when finished</li>
        </ol>
      </Card>

      {/* Features */}
      <div className="grid md:grid-cols-3 gap-4">
        <Card className="p-4">
          <h3 className="font-semibold mb-2">🎤 Speech Recognition</h3>
          <p className="text-sm text-muted-foreground">
            Real-time speech-to-text powered by Google Cloud
          </p>
        </Card>
        <Card className="p-4">
          <h3 className="font-semibold mb-2">🧠 AI Intelligence</h3>
          <p className="text-sm text-muted-foreground">
            Contextual questions generated by Gemini AI
          </p>
        </Card>
        <Card className="p-4">
          <h3 className="font-semibold mb-2">💬 Realistic Avatar</h3>
          <p className="text-sm text-muted-foreground">
            3D avatar with natural lip-sync and expressions
          </p>
        </Card>
      </div>
    </div>
  );
}
